### ISSUE TITLE
how to make it work on the server side, nextjs 14

### ISSUE THREAD

**Issue by emilov2501** [LabEG/Serializable#13]
I want use server side, but I get error when prefetch query
![image](https://github.com/user-attachments/assets/3fef12c7-f6d3-4949-9ff5-d4df441384bc)

**Comment by LabEG** [comment]
Hi. I think you should look for the answer in the questions about NextJS. [For example here](https://github.com/vercel/next.js/issues/47447). This error is a "feature" of NextJS.

**Comment by emilov2501** [comment]
@LabEG Thanks, I will fix this, just to wrap ```structuredClone```
