### ISSUE TITLE
Custom Json-Property names

### ISSUE THREAD

**Issue by telpat0298** [LabEG/Serializable#2]
Awesome library. 
I implemented it today and noticed that it would be useful to have the possibility to choose custom json property names when de/serializeing, since the property names of classes and json won't always be the same.

Greetings
Patrick

**Comment by LabEG** [comment]
I am currently working on a new project and faced with same problem. So I'm going to upgrade this library and add custom names and naming convention as in Newtonsjot Json.

**Comment by LabEG** [comment]
Please check latest version.
