### ISSUE TITLE
Why /dist folder isn't es5 js?

### ISSUE THREAD

**Issue by clicman** [LabEG/Serializable#5]
So it's impossible to use it on nodejs side

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1079535/124545724-bd07f800-de53-11eb-83d0-45bec1c49482.png">

**Comment by LabEG** [comment]
Soon I will fix build system to make two versions of the package, with and without modules.

Right now, you can use @babel/register to solve the problem.

**Comment by LabEG** [comment]
Added to the build is a version of the build with commonjs modules.

Please try.

**Comment by clicman** [comment]
Thanks. Will try it tomorrow!
