### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Zig1375** [LabEG/Serializable#7]
Actually JSON is not an object, but a string and it would be great if the `fromJSON` method can receive a string was well.

```typescript
const json: string = '{"firstName": "John Doe"}';
const user = User.fromJSON( json );
```

because at this moment the code looks like this:
```typescript
const json: string = '{"firstName": "John Doe"}';
const user = User.fromJSON( JSON.parse(json) );
```

**Comment by LabEG** [comment]
Nice feature. I'll add it soon.

**Comment by LabEG** [comment]
Sorry for long response. Lost this issue. I add method fromString and toString. Now you can deserilize direct from string. toString ovverride default toString object method an make serializtion to json string. 
```typescript
const user = User.fromString('{"firstName": "John Doe"}');

fetch("url", {
    method: "POST",
    body: user.toString()
});
```
